// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QrCodeService.proto

package com.yrml.proxima.base.grpc.qrcode;

public interface QrCodeDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QrCodeData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string url = 1;</code>
   */
  java.lang.String getUrl();
  /**
   * <code>string url = 1;</code>
   */
  com.google.protobuf.ByteString
      getUrlBytes();

  /**
   * <code>string method = 2;</code>
   */
  java.lang.String getMethod();
  /**
   * <code>string method = 2;</code>
   */
  com.google.protobuf.ByteString
      getMethodBytes();

  /**
   * <code>string key = 3;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 3;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();

  /**
   * <code>string encryptHex = 4;</code>
   */
  java.lang.String getEncryptHex();
  /**
   * <code>string encryptHex = 4;</code>
   */
  com.google.protobuf.ByteString
      getEncryptHexBytes();
}
