// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QrCodeService.proto

package com.yrml.proxima.base.grpc.qrcode;

public interface QrCodeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:QrCodeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string code = 1;</code>
   */
  java.lang.String getCode();
  /**
   * <code>string code = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>string info = 2;</code>
   */
  java.lang.String getInfo();
  /**
   * <code>string info = 2;</code>
   */
  com.google.protobuf.ByteString
      getInfoBytes();
}
