// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: QrCodeService.proto

package com.yrml.proxima.base.grpc.qrcode;

public final class QrCodeServiceOuterClass {
  private QrCodeServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QrCodeData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QrCodeData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_QrCodeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_QrCodeResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023QrCodeService.proto\"J\n\nQrCodeData\022\013\n\003u" +
      "rl\030\001 \001(\t\022\016\n\006method\030\002 \001(\t\022\013\n\003key\030\003 \001(\t\022\022\n" +
      "\nencryptHex\030\004 \001(\t\",\n\016QrCodeResponse\022\014\n\004c" +
      "ode\030\001 \001(\t\022\014\n\004info\030\002 \001(\t2>\n\rQrCodeService" +
      "\022-\n\rExecuteQrCode\022\013.QrCodeData\032\017.QrCodeR" +
      "esponseB%\n!com.yrml.proxima.base.grpc.qr" +
      "codeP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_QrCodeData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_QrCodeData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QrCodeData_descriptor,
        new java.lang.String[] { "Url", "Method", "Key", "EncryptHex", });
    internal_static_QrCodeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_QrCodeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_QrCodeResponse_descriptor,
        new java.lang.String[] { "Code", "Info", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
